"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Hanken_Grotesk } from "next/font/google";
import "./globals.css";
import { CourseProvider } from "./components/context/CourseContext";
import { TopBanner } from "./components/TopBanner";
import { Navigation } from "./components/Navigation";
import Footer from "./components/Footer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ToastContainer } from "react-toastify";
import { Provider } from "react-redux";
import { store, persistor } from "./store";
import { PersistGate } from "redux-persist/integration/react";
import UserProfileInitializer from "./components/UserProfileInitializer";
import "./styles/scrollbar-hide.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken-grotesk",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Br Collins New",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hankenGrotesk.variable} antialiased`}>
        {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <QueryClientProvider client={queryClient}>
              <CourseProvider>
                <UserProfileInitializer />
                <main className="flex overflow-hidden flex-col bg-white">
                  <TopBanner />
                  <Navigation />
                  {children}
                  <Footer />
                </main>
              </CourseProvider>
              <ToastContainer />
            </QueryClientProvider>
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
